---

workspace:
  base: /go
  path: src/github.com/tinkerbell/boots

pipeline:
  lint:
    group: ci
    image: golangci/golangci-lint:v1.23.8
    commands:
      - golangci-lint run -v -D errcheck

  fmt:
    group: ci
    image: golang:1.13-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - goimports -d . | (! grep .)

  test:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go test -v ./...

  build:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go build

  publish:
    group: publish
    image: plugins/docker
    environment:
      DOCKER_USERNAME:
        from_secret: public_docker_username
      DOCKER_PASSWORD:
        from_secret: public_docker_password
    registry: quay.io
    repo: quay.io/tinkerbell/boots-pr
    tags:
      - ${DRONE_BRANCH/\//-}
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      event: push
    secrets:
      - public_docker_username
      - public_docker_password

  publish_tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/tinkerbell/boots
    tags: ${DRONE_TAG}
    when:
      event: [tag]
    secrets: [docker_username, docker_password]
